// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using final333.MODEL;

#nullable disable

namespace final333.Migrations
{
    [DbContext(typeof(Hoteldbcontext))]
    [Migration("20230526091905_Initia")]
    partial class Initia
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("final333.MODEL.Hotel", b =>
                {
                    b.Property<int>("hotelid")
                        .HasColumnType("int");

                    b.Property<string>("Customeraddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Customername")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("city")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("hotelid");

                    b.ToTable("Hotels");
                });

            modelBuilder.Entity("final333.MODEL.Rooms", b =>
                {
                    b.Property<int>("roomid")
                        .HasColumnType("int");

                    b.Property<string>("amenities")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("availability")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("hotelid")
                        .HasColumnType("int");

                    b.Property<string>("location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("price")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<string>("type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("roomid");

                    b.HasIndex("hotelid");

                    b.ToTable("Rooms");
                });

            modelBuilder.Entity("final333.MODEL.User", b =>
                {
                    b.Property<int>("customerid")
                        .HasColumnType("int");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("customerid");

                    b.ToTable("users");
                });

            modelBuilder.Entity("final333.MODEL.Rooms", b =>
                {
                    b.HasOne("final333.MODEL.Hotel", null)
                        .WithMany("Room")
                        .HasForeignKey("hotelid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("final333.MODEL.Hotel", b =>
                {
                    b.Navigation("Room");
                });
#pragma warning restore 612, 618
        }
    }
}
