// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using final333.MODEL;

#nullable disable

namespace final333.Migrations
{
    [DbContext(typeof(Hoteldbcontext))]
    partial class HoteldbcontextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("final333.MODEL.Hotel", b =>
                {
                    b.Property<int>("hotelid")
                        .HasColumnType("int");

                    b.Property<string>("address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("city")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("hotelid");

                    b.ToTable("Hotels");
                });

            modelBuilder.Entity("final333.MODEL.Reservation", b =>
                {
                    b.Property<int>("reservationid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("reservationid"));

                    b.Property<DateTime>("checkindate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("checkoutdate")
                        .HasColumnType("datetime2");

                    b.Property<int>("customerid")
                        .HasColumnType("int");

                    b.Property<int?>("roomid1")
                        .HasColumnType("int");

                    b.HasKey("reservationid");

                    b.HasIndex("roomid1");

                    b.ToTable("reservations");
                });

            modelBuilder.Entity("final333.MODEL.Rooms", b =>
                {
                    b.Property<int>("roomid")
                        .HasColumnType("int");

                    b.Property<bool>("availability")
                        .HasColumnType("bit");

                    b.Property<int>("capacity")
                        .HasColumnType("int");

                    b.Property<int?>("hotelid1")
                        .HasColumnType("int");

                    b.Property<string>("roomnumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("type")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("roomid");

                    b.HasIndex("hotelid1");

                    b.ToTable("Rooms");
                });

            modelBuilder.Entity("final333.MODEL.Reservation", b =>
                {
                    b.HasOne("final333.MODEL.Rooms", "roomid")
                        .WithMany()
                        .HasForeignKey("roomid1");

                    b.Navigation("roomid");
                });

            modelBuilder.Entity("final333.MODEL.Rooms", b =>
                {
                    b.HasOne("final333.MODEL.Hotel", "hotelid")
                        .WithMany()
                        .HasForeignKey("hotelid1");

                    b.Navigation("hotelid");
                });
#pragma warning restore 612, 618
        }
    }
}
